language: ruby
bundler_args: --without development
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - jruby-19mode
  - jruby-head
  - ruby-head
  - ree
services:
  - mongodb
matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: ree
    - rvm: ruby-head
    - rvm: jruby-head
notifications:
  email: true
script:
  - bundle exec rake spec
before_script:
  - cp config/mongoid.yml.travis config/mongoid.yml
addons:
  code_climate:
    repo_token: 35bcd38cb2dca951597be8b2c58f4c1d25e8f0346e91c575fedb7b8463a10a5c
