defaults: &defaults
  sessions:
    default:
      database: mission_control_<%= Rails.env %>
      hosts:
        - <%= ENV['MONGODB_1_PORT_27017_TCP_ADDR'] %>:<%= ENV['MONGODB_1_PORT_27017_TCP_PROTO'] %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
